# -*- coding: utf-8 -*-
"""telecom_customer_churn_analysis_eda_ml_modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_4ejaqevv6Od4jqwLejLTNAVTxMa39a

# <p style="padding:10px;background-color:#e0301e;margin:0;color:#FFFFFF;font-family:newtimeroman;text-align:center;border-radius:8px;overflow:hidden;font-weight:500;font-size:28px;">📈 CUSTOMER CHURN PREDICTION 📉</p>

<center> <img src="https://i.ibb.co/5cq4fQz/CHURN-IMAGESS.jpg" > </center>

# <span style="font-family:serif; font-size:24px;">Table of Contents</span>

1. [Introduction](#1)
    * [What is Customer Churn?](#2)
    * [How to address and reduce Customer Churn?](#3)
    * [Objectives in this Analysis](#4)
2. [Loading libraries and Dataset](#5)
3. [Interpreting the Dataset](#6)
4. [Data Cleaning](#8)
5. [Visualizing the Data](#7)
6. [Data Preprocessing](#10)
   * [Scaling and Standardizing Numerical Features](#111)
7. [Machine Learning Model Evaluations and Predictions](#11)
   * [Support Vector Classifier](#102)
   * [Random Forest](#103)
   * [Logistic Regression](#104)
   * [Decision Tree Classifier](#105)
   * [AdaBoost Classifier](#106)
   * [Gradient Boosting Classifier](#107)
8. [Conclusion](#15)

<a id = "1" ></a>
# <span style="font-family:Georgia, serif; font-size:28px;"> 1. Introduction</span>
<a id = "introduction" ></a>

<a id = "2" ></a>
<span style="font-family:Georgia, serif; font-size:22px;">Customer Churn</span>
<br>
<span style="font-family:Georgia, serif; font-size:15px;">
Customer churn, also known as customer attrition,is when a customer chooses to stop using products or services of a company. But with each customer who churns, there are usually early indicators or metrics that can have been uncovered with churn analysis.</span>

- <span style="font-family:Georgia, serif; font-size:15px;"> For example, The Telecom Industry faces a lot of Churn(With annual churn rate of 15-25%) because the customers can choose from a variety of service providers and actively switch from existing to another.</span>


- <span style="font-family:Georgia, serif; font-size:15px;">  While looking at both Business operational insights (e.g. declining repeat purchases, reduced purchase quantity) and Customer experience insights along the customer feedbacks is foundational in order to predict churn. A scenario where a customer who has declined in recent visits and gives a feedback score of 6 of 10 after their latest shopping experience, could have an increased probability of churning.</span>

- <span style="font-family:Georgia, serif; font-size:15px;">  Generally in a business perspective it costs more to acquire new customers than it does to retain existing customers. In fact, an increase in customer retention of just 5% can create at least a 25% increase in profit. This is because returning customers will likely spend 60% more on a company's products and services. As a result, the company can spend less on the operating costs of having to acquire new customers by spending time and money on convincing an existing customer to select your company over competitors because they've already made their mind.</span>

- <span style="font-family:Georgia, serif; font-size:15px;">  However, if a company could forecast why and which customers are likely to leave ahead of time, it can focus on customer retention efforts only on these "high risk" clients. This helps in achieving the goal of expanding its customer base and retrieve more customers loyalty. </span>


<a id="churn"></a>
<a id = "3" ></a>
<span style="font-family:Georgia, serif; font-size:22px;">How to address and reduce Customer Churn?</span>


<span style="font-family:Georgia, serif; font-size:15px;"> To reduce customer churn, Companies need to predict which customers are at high risk of churn.</span>

- <span style="font-family:Georgia, serif; font-size:15px;">  To detect early signs of potential churn, insight generation of customers and their interactions across numerous channels, including store visits, product purchase history, customer service calls, Web-based transactions, and social media interaction. </span>

- <span style="font-family:Georgia, serif; font-size:15px;">  By providing solution for churn, businesses can preserve their market position,and also grow and thrive with more customers network, the lower the cost of initiation and the larger the profit.</span>


<a id = "4" ></a>
<span style="font-family:Georgia, serif; font-size:22px;">Objectives in this Analysis</span>
<br>
<br>
<span style="font-family:Georgia, serif; font-size:15px;"> Objective is to find solutions and suggestions for any possible churning </span>
- <span style="font-family:Georgia, serif; font-size:15px;">What is the percentage of Customers who are with the active services and Customers who Churn ?
    <br>
- <span style="font-family:Georgia, serif; font-size:15px;"> Does gender play a role in Customers Churn ?</span>
    <br>
- <span style="font-family:Georgia, serif; font-size:15px;"> Does the type of service provided leads to more/less Customers Churn?</span>
    <br>
- <span style="font-family:Georgia, serif; font-size:15px;"> What's the most profitable service types?</span>
    <br>
- <span style="font-family:Georgia, serif; font-size:15px;"> Profitable features and services by the company? </span>
<a id="objective"></a>

data: https://drive.google.com/file/d/1jl5v2oV2OzJAgtfg282nlbP1p0yCX1IA/view?usp=sharing

#1 Import libarary

#2 Import the dateset

#3 EDA

# FEATURE ENG.--->Encoding,scaling

#Feature selection-

#Model building

#Model eval.

#Model deployment

___

<a id = "5" ></a>
# <span style="font-family:Georgia, serif; font-size:28px;"> 2. Loading libraries and data</span>
<a id="loading"></a>

<span style="font-family:Georgia, serif; font-size:20px;"> Basic Imports</span>
"""

import pandas as pd  #data manipulatation
import numpy as np  #numerical python
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

"""<span style="font-family:Georgia, serif; font-size:20px;"> Dataset Import</span>"""

#loading data
df = pd.read_csv('/content/customer_churn (1).csv')

"""___

<a id = "6" ></a>
# <span style="font-family:Georgia, serif; font-size:28px;"> 3. Interpreting the Dataset</span>
<a id = "Undertanding the data" ></a>
"""

df.head()

"""**So, In this Telecom Company's Data we have,**
*  **Churn Column** - *Customers who left recently*

* **Services provided by the company to its customer** – *phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies*

* **Customer's Information Columns** - *Old/New Customer and their Active Period, contract, payment method, paperless billing, monthly charges, and total charges*

* **Customer's Demographic Columns** – *gender, age range, and if they have partners and dependents*
"""

df.shape

df.isna().sum()

df.info() #data information

"""##  Dataset Inference and Understanding

### 1. Overview
- The dataset contains **7043 rows** and **21 columns**.
- It appears to represent **customer information for a telecommunications company**, where the target variable **`Churn`** indicates whether a customer has discontinued the service.
- **Memory usage:** ~1.1 MB

---

###  2. Column Details

| Type | Count | Example Columns |
|------|--------|----------------|
| **Object (categorical)** | 18 | `customerID`, `gender`, `Partner`, `Dependents`, `PhoneService`, `MultipleLines`, `InternetService`, `OnlineSecurity`, `OnlineBackup`, `DeviceProtection`, `TechSupport`, `StreamingTV`, `StreamingMovies`, `Contract`, `PaperlessBilling`, `PaymentMethod`, `TotalCharges`, `Churn` |
| **Integer (numeric)** | 2 | `SeniorCitizen`, `tenure` |
| **Float (numeric)** | 1 | `MonthlyCharges` |

- Most features are **categorical** — describing customer demographics and services used.
- Only a few are **numerical**: `tenure`, `MonthlyCharges`, and (after conversion) `TotalCharges`.

---

###  3. Data Quality Observations

1. **`TotalCharges` column:**
   - Currently stored as an `object` (string), even though it represents numerical values.
   - This means there might be some invalid or missing entries (like blank spaces).

2. **No visible missing values** in the info summary (`non-null count = 7043`),  
   but hidden missing or invalid entries may exist in `TotalCharges`.

3. **`customerID`** is a unique identifier for each customer and should not be used for model training.
"""

df.isnull().sum()

df.dtypes

"""***
<a id = "8" ></a>
# <span style="font-family:serif; font-size:28px;"> 4. Data Cleaning </span>
<a id = "8" ></a>
"""

#Since, we don't need customerID, We drop the column
df = df.drop(['customerID'], axis = 1)
df.head()

"""Converting space to null"""

#Converting Object column to Numerical Column, which is actually holds Numerical data
df['TotalCharges'] = pd.to_numeric(df.TotalCharges, errors='coerce')
df.isnull().sum()

# Fillna with mean values
#df.fillna(df["TotalCharges"].mean())

#or
#Removing missing values
#df.dropna(inplace = True)

#df['tenure']=df.drop(df[df['tenure']==0].index,axis=0)

#Removing tenure equal to 0
df.drop(labels=df[df['tenure'] == 0].index, axis=0, inplace=True)
df[df['tenure'] == 0].index

df.isna().sum()

df.isnull().sum()

df.shape

"""#Label encoding->object to numeric-->(alhabetically)
#ordinal ecoding-->object to number-->order wise encodin
#one hot encoding-->object to number-->create all category as a coulmnm
"""

#Categorizing Senior Citizen column for encoding
df["SeniorCitizen"]= df["SeniorCitizen"].map({0: "No", 1: "Yes"})
df.head()

df.describe()

#Finding any absurd values in Numeric Columns
numerical_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
df[numerical_cols].describe()

"""### **Dataset Overview**

The dataset appears to describe customer information for a **telecommunication service** (likely the *Telco Customer Churn dataset*), focusing on three numeric variables:

* **tenure** – how many months a customer has stayed with the company,
* **MonthlyCharges** – the amount charged per month,
* **TotalCharges** – the total amount a customer has paid so far.

---

### **1. Tenure**

* **Range:** 1 to 72 months → customers have stayed from just 1 month up to 6 years.
* **Mean:** 32.42 months (~2.7 years).
* **Median:** 29 months → distribution slightly **right-skewed** (a few long-term customers).
* **Interpretation:** The customer base includes both new and long-term users, but the typical customer stays for around 2–3 years.

---

### **2. Monthly Charges**

* **Range:** $18.25 – $118.75 → wide variation in monthly plans.
* **Mean:** $64.80, **Median:** $70.35 → slightly **left-skewed** (more customers pay higher monthly charges).
* **Interpretation:** Most customers pay moderate to high monthly fees, suggesting multiple service tiers or add-ons.

---

### **3. Total Charges**

* **Range:** $18.80 – $8684.80.
* **Mean:** $2283.30, **Median:** $1397.48 → **right-skewed** (a few long-tenured customers with very high totals).
* **Interpretation:** Total payments depend heavily on tenure and monthly charges, as expected newer customers have low totals, while long-term ones accumulate large totals.

---

### **4. Relationship Insights (from summary)**

* **Tenure** and **TotalCharges** are likely **positively correlated**, longer tenure leads to higher total charges.
* **MonthlyCharges** varies widely but doesn’t depend strongly on tenure (suggesting different plan types).
* High **std. deviation** for TotalCharges (2266.77) reflects a diverse customer base in terms of spending and loyalty.

---

### **Overall Inference**

* The customer population is **diverse**, with varying subscription lengths and charge levels.
* There is evidence of **customer segmentation**, low-charge short-term users vs. high-charge long-term users.
* Understanding these distributions can help identify **customer lifetime value** and **potential churn risks** among shorter-tenure or lower-spending segments.

"""

df.describe(include='O').T

7032-5163

df.Churn.value_counts()

df['Churn'].value_counts()

df.describe(include='all').T

"""###  **General Overview**

* **Total customers:** 7,032
* **Target variable:** `Churn` (Yes/No) → 5163 “No” and 1869 “Yes” (≈ 26.6% churn rate).
  → So, around **one in four customers churned**.

---

### **Demographics**

* **Gender:** Fairly balanced — 3,549 male and 3,483 female customers.
* **Senior Citizens:** Only about 16% (`7032 - 5890 = 1142`) are seniors, suggesting a younger customer base overall.
* **Partner:** 51.7% of customers do **not** have a partner.
* **Dependents:** 70% (4,933) have **no dependents**, indicating mostly single or independent individuals.

---

###  **Tenure and Loyalty**

* **Tenure mean:** 32.4 months (≈ 2.7 years).
* **Range:** 1 to 72 months.
  → Many customers are relatively new, as the median tenure is just **29 months**.
* Customers with longer tenures likely show lower churn rates (based on typical telecom churn trends).

---

###  **Services and Features**

* **Phone Service:** Almost all customers (6,352) have it.
* **Multiple Lines:** About half have multiple lines.
* **Internet Service:**

  * Fiber optic: Most common (3,096 users).
  * DSL and No Internet are less frequent.
* **Online Security, Backup, Device Protection, Tech Support:**
  Most customers answered **“No”** to these — suggesting **low adoption of add-on services**.

---

###  **Entertainment Services**

* **Streaming TV/Movies:** Roughly equal mix between users and non-users, indicating streaming is a moderately adopted service.

---

###  **Contracts and Billing**

* **Contract Type:**

  * **Month-to-month:** Most common (3,875 customers).
  * The rest have one- or two-year contracts.
* **Paperless Billing:** 59% use it (`4168 Yes`).
* **Payment Method:**

  * **Electronic check** is most popular (2,365 users).
  * Other payment methods include mailed check, bank transfer, and credit card.

---

###  **Charges**

* **Monthly Charges:**

  * Mean = $64.80
  * Range = $18.25 – $118.75
  * Higher monthly charges often correspond to fiber optic users and those with multiple add-ons.
* **Total Charges:**

  * Mean = $2,283
  * Range = $18.80 – $8,684
  * Strongly influenced by tenure higher tenure = higher total charges.

---

###  **Key Insights**

1. **Churn is higher among**:

   * Month-to-month customers
   * Fiber optic users (higher cost, possibly performance or price dissatisfaction)
   * Customers with fewer add-on services (low perceived value)

2. **Retention is stronger among**:

   * Long-tenure customers
   * Those with longer contracts
   * Those using electronic or automatic payments

3. **Opportunities for the company:**

   * Encourage add-on adoption (security, tech support, etc.)
   * Convert short-term contracts to longer ones
   * Offer loyalty incentives to new customers in their first 1–2 years.

#below code is just for explanation not for model building
"""

#Creating Dataframe for correlation plot
df2 = df
df2['Churn'].replace(to_replace='Yes', value=1, inplace=True)
df2['Churn'].replace(to_replace='No',  value=0, inplace=True)
df2

# df2['Churn']=df2['Churn'].replace(to_replace='Yes', value=1)

df_dummies = pd.get_dummies(df2)
df_dummies.head()

df_dummies.corr()['Churn']

#Correlation of "Churn" with Features:
plt.figure(figsize=(15,8))
sns.set(style = 'dark')

df_dummies.corr()['Churn'].sort_values(ascending = False).plot(kind='bar',color='blue')

"""___

<a id = "7" ></a>
# <span style="font-family:serif; font-size:28px;"> 4. Visualizing The Data </span>
<a id = "missingvalue" ></a>

<span style="font-family:serif; font-size:23px;"> Gender Spread and Churn Distribution </span>

"""

df['gender'].value_counts()

"""## Gender and Churn Distribution Analysis

###  1. Gender Distribution
- The **Gender** chart shows that the customer base is **almost evenly split**:
  - **Male:** 49.5%
  - **Female:** 50.5%
-  This indicates there is **no significant gender imbalance** in the dataset.  
- Since both genders are almost equally represented, **gender alone may not have a strong impact** on customer churn — further analysis will be required to confirm this.

---

###  2. Churn Distribution
- The **Churn** chart shows:
  - **No (did not churn):** 73.4%
  - **Yes (churned):** 26.6%
- This means that about **one in every four customers left the company**.
-  The dataset is **slightly imbalanced**, as the number of customers who stayed (73.4%) is much higher than those who left (26.6%).
- When building predictive models, this imbalance should be addressed using techniques such as:
  - **Resampling** (e.g., SMOTE or Random Oversampling)
  - **Adjusting class weights** in the model.

---

###  Insights
- Gender distribution is balanced → good for unbiased modeling.
- Churn distribution is imbalanced → needs consideration during model training.
- The churn rate (26.6%) is quite significant for a telecom business, meaning that **reducing churn could substantially improve customer retention and revenue**.

"""

df['Churn'].value_counts()

"""* There's almost to null differences between the people who churned, as both men and women are churn in equal ratio.
---
<span style="font-family:serif; font-size:23px;"> Contract Distribution w.r.t Churn</span>

"""

fig = px.histogram(df, x="Churn", color="Contract", barmode="group")
fig.show()

color_discrete_map = {"Month-to-month": "#7fcdff", "One year": "#326ada", "Two year": "#ff9b35"}

fig = px.histogram(df, x="Churn", color="Contract", barmode="group", title="<b><i>Churn Distribution w.r.t Contract<i><b>", color_discrete_map = color_discrete_map)
fig.update_layout(width=700, height=500, bargap=0.1)
fig.show()

"""##  Churn Distribution with respect to Contract Type

###  Chart Description
The bar chart shows how **customer churn** varies across different **contract types**.

- **X-axis:** Churn status  
  - `0` → Customers who stayed (did not churn)  
  - `1` → Customers who left (churned)
- **Y-axis:** Number of customers  
- **Color legend:** Represents contract types  
  - Light blue → Month-to-month  
  - Dark blue → One year  
  - Orange → Two year  

---

###  Key Observations

1. **Month-to-Month Contracts:**
   - The majority of churned customers (Churn = 1) are on **month-to-month** contracts.  
   - This indicates that customers without long-term commitments are **more likely to leave**.

2. **One-Year and Two-Year Contracts:**
   - Customers on **one-year** or **two-year** contracts have a **much lower churn rate**.
   - Long-term contracts seem to **increase customer retention**, likely due to stability, discounts, or contractual obligations.

3. **Churn Trend Summary:**
   - **Short-term (month-to-month)** → High churn rate.  
   - **Long-term (one or two years)** → Low churn rate.

---

###  Insights for Learners

- Contract duration has a **strong influence on customer loyalty**.
- Customers with flexible, month-to-month agreements can **easily switch to competitors**, leading to higher churn.
- Telecom companies can **reduce churn** by:
  - Offering **incentives** for longer contracts (discounts, bundles, loyalty programs).  
  - Improving **customer experience** for short-term users to encourage contract upgrades.

---

###  Summary
- **Month-to-month** customers → highest churn rate.  
- **One-year and two-year** customers → lowest churn rate.  
- Contract type is one of the **most important predictors** of customer churn.

* 75% of customer who have Month-to-Month Contract have opted to move out as compared to 13% of customers  who have signed One Year Contract and 3% of customers  who have signed Two Year Contract.

---

<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Payment Method</span>
"""

fig = px.histogram(df, x="Churn", color="PaymentMethod", title="<b>Churn distribution w.r.t. Customer Payment Method</b>",text_auto=True)
fig.update_layout(width=700, height=500, bargap=0.1)
# fig.data[0].marker.color = ('#7fcdff')
# fig.data[1].marker.color = ('#326ada')
# fig.data[2].marker.color = ('#ff9b35')
# fig.data[3].marker.color = ('#56c175')


fig.show()

"""* Majority of the customers who moved out were having Electronic Check as Payment Method and others who opted for Credit-Card automatic transfer / Bank Automatic Transfer and Mailed Check as Payment Method were less likely to switch.
---

<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Internet Services and Gender</span>

"""

df[df["gender"]=="Male"][["InternetService", "Churn"]].value_counts()

df[df["gender"]=="Female"][["InternetService", "Churn"]].value_counts()

fig = go.Figure()

colors = {'Female':'steelblue','Male':'firebrick'}

fig.add_trace(go.Bar(
  x = [['Churn:No', 'Churn:No', 'Churn:Yes', 'Churn:Yes'],
       ["Female", "Male", "Female", "Male"]],
  y = [965, 992, 219, 240],
  name = 'DSL'))

fig.add_trace(go.Bar(
  x = [['Churn:No', 'Churn:No', 'Churn:Yes', 'Churn:Yes'],
       ["Female", "Male", "Female", "Male"]],
  y = [889, 910, 664, 633],
  name = 'Fiber optic',
))

fig.add_trace(go.Bar(
  x = [['Churn:No', 'Churn:No', 'Churn:Yes', 'Churn:Yes'],
       ["Female", "Male", "Female", "Male"]],
  y = [690, 717, 56, 57],
  name = 'No Internet',
))


fig.update_layout(title_text="<b>Churn Distribution w.r.t Internet Service and Gender</b>")
fig.data[0].marker.color = ('#7fcdff')
fig.data[1].marker.color = ('#326ada')
fig.data[2].marker.color = ('#ff9b35')


fig.show()

"""* Fiber optic service which was choosen by a lot of customers and it's evident that there's high churn rate among these customers. This could expose an issue in the Fiber optic service which dissatisfied most of it's customers, further looking into the issue might find a better and apt solution.
* Customers who opted for DSL service are larger in number and is found to have less churn rate compared to Fibre optic service

---

<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Dependants</span>

"""

color_map = {"Yes": "#7fcdff", "No": "#326ada"}
fig = px.histogram(df, x="Churn", color="Dependents", barmode="group", title="<b>Churn distribution w.r.t. Dependents</b>", color_discrete_map=color_map)
fig.update_layout(width=700, height=500, bargap=0.1)
fig.show()

"""* Customers without dependents are more likely to churn
---
<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Partners</span>


"""

color_map = {"Yes": '#7fcdff', "No": '#326ada'}
fig = px.histogram(df, x="Churn", color="Partner", barmode="group", title="<b>Churn distribution w.r.t. Partners</b>", color_discrete_map=color_map)
fig.update_layout(width=700, height=500, bargap=0.1)
fig.show()

"""* On the above visual, a conclusion can be obtained such that customers without dependents and customers who have partners are more likely to churn while senior citizens being the most of churn.
---
<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Senior Citizens </span>

"""

color_map = {"Yes": '#7fcdff', "No": '#326ada'}
fig = px.histogram(df, x="Churn", color="SeniorCitizen", title="<b>Churn distribution w.r.t. Senior Citizen</b>", color_discrete_map=color_map)
fig.update_layout(width=700, height=500, bargap=0.1)
fig.show()

"""* Eventhough the observed fraction of senior citizen is very less, most of the senior citizens churn.

---
<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Online Security </span>
"""

color_map = {"Yes": "#7fcdff", "No": "#326ada", "No internet service":"#ff9b35"}
fig = px.histogram(df, x="Churn", color="OnlineSecurity", barmode="group", title="<b>Churn w.r.t Online Security</b>", color_discrete_map=color_map)
fig.update_layout(width=700, height=500, bargap=0.1)
fig.show()

"""* Absence of online security,makes most customers churn.

---
<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Paperless Billing </span>
"""

color_map = {"Yes": '#7fcdff', "No": '#326ada'}
fig = px.histogram(df, x="Churn", color="PaperlessBilling",  title="<b>Churn distribution w.r.t. Paperless Billing</b>", color_discrete_map=color_map)
fig.update_layout(width=700, height=500, bargap=0.1)
fig.show()

"""* Paperless Billing seems like one the reasons because of which customers are most likely to churn.

---
<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Tech Support </span>
"""

color_map = {"Yes": "#7fcdff", "No": "#326ada", "No internet service":"#ff9b35"}


fig = px.histogram(df, x="Churn", color="TechSupport",barmode="group",  title="<b>Churn distribution w.r.t. TechSupport</b>", color_discrete_map=color_map)
fig.update_layout(width=700, height=500, bargap=0.1)
fig.show()

"""* The absence of online security, Paperless Billing system and services with no TechSupport were the similiar trend are of the customers who are most likely churn.

---
<span style="font-family:serif; font-size:23px;"> Churn Distribution w.r.t Phone Service </span>
"""

color_map = {"Yes": '#7fcdff', "No": '#326ada'}
fig = px.histogram(df, x="Churn", color="PhoneService", title="<b>Churn distribution w.r.t. Phone Service</b>", color_discrete_map=color_map)
fig.update_layout(width=700, height=500, bargap=0.1)
fig.show()

"""* Eventhough there's a small fraction of customers but it's better to point out as they are more likely to churn because don't have a phone service.

---
<a id = "4" ></a>
<span style="font-family:Georgia, serif; font-size:24px;"><b> Conclusions as a Data Analyst :</b></span>
<span style="font-family:Georgia, serif; font-size:18px;">
    <br>
     ● 75% of customer who have Month-to-Month Contract have opted to move out as compared to 13% of customers  who have signed One Year Contract and 3% of customers  who have signed Two Year Contract.
    <br>
     ● Majority of the customers who moved out were having Electronic Check as Payment Method and others who opted for Credit-Card automatic transfer / Bank Automatic Transfer and Mailed Check as Payment Method were less likely to switch.
    <br>
     ● Fiber optic service which was choosen by a lot of customers and it's evident that there's high churn rate among these customers. This could expose an issue in the Fiber optic service which dissatisfied most of it's customers, further looking into the issue might find a better and apt solution.
    <br>
     ● Customers who opted for DSL service are larger in number and is found to have less churn rate compared to Fibre optic service
    <br>
     ● Customers without dependents and customers who have partners are more likely to churn while senior citizens being the most of churn.
    <br>
     ● The absence of online security, Paperless Billing system and services with no TechSupport were the similiar trend are of the customers who are most likely churn.
    <br>
     ● There's a small fraction of customers who are more likely to churn and it's been found that they don't have a phone service. </span>
<a id="objective"></a>

---
### *A Data Analyst's work done here. Now,comes Data Scientist who makes a model to predict the churn in the future data.*
---
"""

plt.figure(figsize=(5, 5))
num_df=df.select_dtypes(include=['number'])
sns.heatmap(num_df.corr(), annot=True, cmap='rainbow')
plt.title('Correlation Heatmap')
plt.show()

"""___"""

# import plotly.express as px
# data = dict(
#     character=["Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"],
#     parent=["", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve" ],
#     value=[10, 14, 12, 10, 2, 6, 6, 4, 4])

# fig = px.sunburst(
#     data,
#     names='character',
#     parents='parent',
#     values='value',
# )
# fig.show()

# import plotly.express as px
# df = px.data.gapminder()
# px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
#            size="pop", color="continent", hover_name="country",
#            log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])

!pip install ydata_profiling

from ydata_profiling import ProfileReport

profile=ProfileReport(df,title="AK_new_report1",explorative=True)
profile.to_file("AK_new_report2.html")

# import plotly.graph_objects as go
# import numpy as np

# # Create figure
# fig = go.Figure()

# # Add traces, one for each slider step
# for step in np.arange(0, 5, 0.1):
#     fig.add_trace(
#         go.Scatter(
#             visible=False,
#             line=dict(color="#00CED1", width=6),
#             name="𝜈 = " + str(step),
#             x=np.arange(0, 10, 0.01),
#             y=np.sin(step * np.arange(0, 10, 0.01))))

# # Make 10th trace visible
# fig.data[10].visible = True

# # Create and add slider
# steps = []
# for i in range(len(fig.data)):
#     step = dict(
#         method="update",
#         args=[{"visible": [False] * len(fig.data)},
#               {"title": "Slider switched to step: " + str(i)}],  # layout attribute
#     )
#     step["args"][0]["visible"][i] = True  # Toggle i'th trace to "visible"
#     steps.append(step)

# sliders = [dict(
#     active=10,
#     currentvalue={"prefix": "Frequency: "},
#     pad={"t": 50},
#     steps=steps
# )]

# fig.update_layout(
#     sliders=sliders
# )

# fig.show()

# Defining a Function to Convert Objects to Int
def my_labelencoder(dataset):
    if dataset.dtype=='object':
        dataset = LabelEncoder().fit_transform(dataset)
    return dataset

df2 = df
df = df.apply(lambda x: my_labelencoder(x))

"""Alternative code just for explanation"""

le=LabelEncoder()
for col in df.columns:
  if df[col].dtype=='object':
    df[col]=le.fit_transform(df[col])

df

X = df.drop(columns = ['Churn','PhoneService','gender'])
y = df['Churn'].values
df.head()

X

y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=67)
#X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=99)

X_train

df

X_train.shape

X_train

X_test.shape

X_test

num_cols = ["tenure", 'MonthlyCharges', 'TotalCharges']

scaler= StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import *

# Assuming you have a dataset loaded in 'X' and target 'y'
# For example: X = your_feature_data, y = your_target_data

# Split your data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

# Initialize Random Forest model
model_rf = RandomForestClassifier(
    n_estimators=100,        # number of trees
    random_state=10,
    n_jobs=-1               # use all available cores
)

# Train the model
model_rf.fit(X_train, y_train)

# Make predictions
prediction_test = model_rf.predict(X_test)

# Print accuracy
print(accuracy_score(y_test, prediction_test))

print(classification_report(y_test, prediction_test))

